### ISSUE TITLE
E.D.A

### ISSUE THREAD

**Issue by redpinecube** [LukaTosic09/Forecasting-2024-Election#5]
initial variables of interest for a simple bayesian hierarchical model :

- pollscore
- state
- days till election 
- sample size
- name
- pct

**Comment by redpinecube** [comment]
graphs for the data section and better exploration of the dataset is necessary.

**Comment by LukaTosic09** [comment]
Yep, I agree. The data section wasn't done, I just pushed it for Sakura to be able to see the most up to date version
